# Generated by Django 5.0.11 on 2025-03-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
