# Generated by Django 5.0.11 on 2025-03-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0004_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passenger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_three.passenger'),
        ),
    ]
