# Generated by Django 5.0.11 on 2025-03-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0005_alter_passport_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_three.passenger'),
        ),
    ]
