# Generated by Django 5.0.11 on 2025-03-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0008_alter_b_options_b_name2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B',
            new_name='C',
        ),
    ]
