# Generated by Django 5.0.11 on 2025-03-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0009_rename_b_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c',
            options={'verbose_name': 'singular', 'verbose_name_plural': 'plural'},
        ),
    ]
