# Generated by Django 5.0.11 on 2025-03-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0011_alter_c_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c',
            options={'ordering': ['age', 'name2'], 'verbose_name': 'singular', 'verbose_name_plural': 'plural'},
        ),
    ]
