# Generated by Django 5.0.11 on 2025-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0012_alter_c_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('age2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'singular',
                'verbose_name_plural': 'plural',
                'ordering': ['age2', 'name2'],
                'abstract': False,
            },
        ),
    ]
