# Generated by Django 5.0.11 on 2025-03-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_three', '0016_alter_c_relationship_alter_d_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sB', to='app_three.dog'),
        ),
        migrations.AlterField(
            model_name='d',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sB', to='app_three.dog'),
        ),
    ]
