# Generated by Django 5.0.11 on 2025-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0003_remove_book_author_authorbooksthrough_author_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorbooksthrough',
            name='whatever_through_field',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='authorbooksthrough',
            unique_together={('author', 'book')},
        ),
    ]
