# Generated by Django 5.0.11 on 2025-03-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0004_alter_authorbooksthrough_whatever_through_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_query_name='book', through='app_two.AuthorBooksThrough', to='app_two.book'),
        ),
    ]
