# Generated by Django 5.0.11 on 2025-03-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0005_alter_author_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authorr', related_query_name='authorq', through='app_two.AuthorBooksThrough', to='app_two.book'),
        ),
    ]
