# Generated by Django 5.0.11 on 2025-03-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0006_alter_author_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='app_two.AuthorBooksThrough', to='app_two.book'),
        ),
    ]
